# Generated by Django 5.1.1 on 2024-09-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=None, verbose_name='Cholesterol (mg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=None, verbose_name='Dietary Fibre (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=None, verbose_name='Protein (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=None, verbose_name='Sodium (mg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=None, verbose_name='Sugar (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbohydrate',
            field=models.FloatField(default=None, verbose_name='Total Carbohydrate (g)'),
            preserve_default=False,
        ),
    ]
